"""Add image_url to Scenario

Revision ID: b73b03169417
Revises: 2026_04_28_section_unit_lesson_dictionary_audio
Create Date: 2026-04-28 10:20:39.120644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b73b03169417'
down_revision: Union[str, None] = '2026_04_28_section_unit_lesson_dictionary_audio'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_transactions_user_created'), table_name='coin_transactions')
    op.drop_index(op.f('ix_learning_levels_active_order'), table_name='learning_sections')
    op.create_index('ix_learning_sections_active_order', 'learning_sections', ['is_active', 'order_index'], unique=False)
    op.drop_index(op.f('ix_exercise_attempts_user_exercise_created'), table_name='lesson_attempts')
    op.create_index('ix_lesson_attempts_user_lesson_created', 'lesson_attempts', ['user_id', 'lesson_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_lesson_exercises_lesson_active_order'), table_name='lessons')
    op.drop_constraint(op.f('uq_lesson_exercises_lesson_order'), 'lessons', type_='unique')
    op.create_index('ix_lessons_unit_active_order', 'lessons', ['unit_id', 'is_active', 'order_index'], unique=False)
    op.create_unique_constraint('uq_lessons_unit_order', 'lessons', ['unit_id', 'order_index'])
    op.add_column('scenarios', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.alter_column('scenarios', 'tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_lessons_level_active_order'), table_name='units')
    op.drop_constraint(op.f('uq_lessons_level_order'), 'units', type_='unique')
    op.create_index('ix_units_section_active_order', 'units', ['section_id', 'is_active', 'order_index'], unique=False)
    op.create_unique_constraint('uq_units_section_order', 'units', ['section_id', 'order_index'])
    op.drop_index(op.f('ix_user_exercise_progress_user_status'), table_name='user_lesson_progress')
    op.drop_constraint(op.f('uq_user_exercise_progress_user_exercise'), 'user_lesson_progress', type_='unique')
    op.create_index('ix_user_lesson_progress_user_status', 'user_lesson_progress', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_user_lesson_progress_user_lesson', 'user_lesson_progress', ['user_id', 'lesson_id'])
    op.drop_index(op.f('ix_user_lesson_progress_user_status'), table_name='user_unit_progress')
    op.drop_constraint(op.f('uq_user_lesson_progress_user_lesson'), 'user_unit_progress', type_='unique')
    op.create_index('ix_user_unit_progress_user_status', 'user_unit_progress', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_user_unit_progress_user_unit', 'user_unit_progress', ['user_id', 'unit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_unit_progress_user_unit', 'user_unit_progress', type_='unique')
    op.drop_index('ix_user_unit_progress_user_status', table_name='user_unit_progress')
    op.create_unique_constraint(op.f('uq_user_lesson_progress_user_lesson'), 'user_unit_progress', ['user_id', 'unit_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_lesson_progress_user_status'), 'user_unit_progress', ['user_id', 'status'], unique=False)
    op.drop_constraint('uq_user_lesson_progress_user_lesson', 'user_lesson_progress', type_='unique')
    op.drop_index('ix_user_lesson_progress_user_status', table_name='user_lesson_progress')
    op.create_unique_constraint(op.f('uq_user_exercise_progress_user_exercise'), 'user_lesson_progress', ['user_id', 'lesson_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_exercise_progress_user_status'), 'user_lesson_progress', ['user_id', 'status'], unique=False)
    op.drop_constraint('uq_units_section_order', 'units', type_='unique')
    op.drop_index('ix_units_section_active_order', table_name='units')
    op.create_unique_constraint(op.f('uq_lessons_level_order'), 'units', ['section_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lessons_level_active_order'), 'units', ['section_id', 'is_active', 'order_index'], unique=False)
    op.alter_column('scenarios', 'tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('scenarios', 'image_url')
    op.drop_constraint('uq_lessons_unit_order', 'lessons', type_='unique')
    op.drop_index('ix_lessons_unit_active_order', table_name='lessons')
    op.create_unique_constraint(op.f('uq_lesson_exercises_lesson_order'), 'lessons', ['unit_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lesson_exercises_lesson_active_order'), 'lessons', ['unit_id', 'is_active', 'order_index'], unique=False)
    op.drop_index('ix_lesson_attempts_user_lesson_created', table_name='lesson_attempts')
    op.create_index(op.f('ix_exercise_attempts_user_exercise_created'), 'lesson_attempts', ['user_id', 'lesson_id', 'created_at'], unique=False)
    op.drop_index('ix_learning_sections_active_order', table_name='learning_sections')
    op.create_index(op.f('ix_learning_levels_active_order'), 'learning_sections', ['is_active', 'order_index'], unique=False)
    op.create_index(op.f('ix_coin_transactions_user_created'), 'coin_transactions', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
